version: '2'
services:
    ezcomptesmicroserviceuaaserver-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/ezcomptesMicroserviceUaaServer/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ezcomptesMicroserviceUaaServer
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
